name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Clone Repository
    
    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashfiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Install TFLint
    
    - name: Show Version
      run: tflint --version
    
    - name: Install Plugins
      run: tflint --init
    
    - name: Run TFLint
      run: tflint -f compact

  tfsec:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.2

  terraform-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Validate README with terraform-docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        fail-on-diff: true

  terratest:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.3
    - name: Setup Terraform
      uses: autero1/action-terraform@v1.1.0
      with:
        terraform_version: 1.3.5
    - name: Download Go Modules
      working-directory: test
      run: go mod download
    - name: Run Terratests
      working-directory: test
      run: go test -v
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
